services:
  - type: web
    name: ev-charge-hub-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run migrate && npm run seed
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL
        value: require
      - key: CLIENT_URL
        sync: false
      - key: DEMO_MODE
        value: "true"
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
